student_ids = {1, 2, 3, 4, 5}
print(student_ids)
print(type(student_ids))
student_ids.add(6)
print(student_ids)
print(student_ids.pop())
print(student_ids)
student_ids.clear()
print(student_ids)
student_ids.add(7)